### ISSUE TITLE
Run single step by name

### ISSUE THREAD

**Issue by Wolfsrudel** [cloud66-oss/trackman#10]
It would be cool if you could run a single step by name (like the `targets` for `make`). Is it planned to add something there, or does that make no sense in terms of executing workflows?

**Comment by khash** [comment]
Thank you for the suggestion. I think being able to run a single step by name can be useful for debugging purposes however it might pose challenges when steps are interdependents. Starting the whole workflow from a place other than the beginning can also be useful.
