### ISSUE TITLE
Provide a way to perform cleanup

### ISSUE THREAD

**Issue by MChorfa** [cloud66-oss/trackman#2]
Hey, 
Thank you for this project. Is there a do cleanup tasks? Like in terraform way ``` terraform destroy``` or do we have to rewrite the whole steps backward.
Thanks

**Comment by khash** [comment]
Since each step is a custom script provided by the user, reversing its effects is not possible automatically. However I can imagine support for a "revert" command which would be provided by the user and is run to reverse the actions.

**Comment by MChorfa** [comment]
Thank you for your feedback
