### ISSUE TITLE
workflow metadata not available within step

### ISSUE THREAD

**Issue by santhosh60** [cloud66-oss/trackman#5]
The step 'dump' has access to only the metadata 'foo' which is declared at the step level and does not have access to 'fizz' which is declared at the workflow level.
is it supported and if so please guide me in accessing the metadata at the workflow level from the go templates defined in a step command.

### input:
```yaml
version: 1
metadata:
  fizz: buzz
steps:
  - name: dump
    metadata:
      foo: bar
    command: "echo {{ index .Metadata }}"
```

### output:
```
INFO[0000] Running Preflight checks
INFO[0000] Preflight checks complete
INFO[0000] Starting                                      Step=dump
DEBU[0000] Running                                       Step=dump
DEBU[0000] map[foo:bar]                                  Step=dump
INFO[0000] Successfully finished                         Step=dump
INFO[0000] Done
```

**Comment by khash** [comment]
`MergedMetadata` is added to the dev branch and will be merged into master and released soon.
