### ISSUE TITLE
Allow step environment variables

### ISSUE THREAD

**Issue by khash** [cloud66-oss/trackman#6]
Following #3 it should be possible to assign environment variables to a specific step. This should be added to the step API.

**Comment by santhosh60** [comment]
Step environment variables are not working as expected,

input:
```yaml
version: 1
steps:
  - name: echo
    env: ["FOO=BAR"]
    command: echo $FOO
```

output:
```
INFO[0000] Running Preflight checks
INFO[0000] Preflight checks complete
INFO[0000] Starting                                      Step=echo
DEBU[0000] Running                                       Step=echo
DEBU[0000]                                               Step=echo
INFO[0000] Successfully finished                         Step=echo
INFO[0000] Done
```

**Comment by khash** [comment]
When you run `echo` the environment variable is used from the current process as echo is an internal command in bash. To test and see how the environment variable is passed into a separate process, try `env.yml` in the `samples` folder. If you would like to use environment variables in bash built in commands, you can change the command to `bash -c ....` instead.
